name: Build EKS snap on PR and push to master

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Create snap package
    runs-on: ubuntu-latest

    steps:
    - name: Checking out repo
      uses: actions/checkout@v2
    - name: Install lxd
      run: |
        sudo lxd init --auto
        sudo usermod --append --groups lxd $USER
        sg lxd -c 'lxc version'
    - name: Install snapcraft
      run: sudo snap install snapcraft --classic
    - name: Build snap
      run: |
        sg lxd -c 'snapcraft --use-lxd'
        sudo mv eks*.snap eks.snap
    - name: Uploading snap
      uses: actions/upload-artifact@v3.0.0
      with:
        name: eks.snap
        path: eks.snap
    - name: Running addons tests
      run: |
        set -x
        sudo snap install *.snap --classic --dangerous
        ./tests/smoke-test.sh
